baseurl: '/'
permalink: pretty
title: 'VDKMS'

logo:
  mobile: "images/logo/logo.svg"
  mobile_height: "20px"
  mobile_width: "auto"
  desktop: "images/logo/logo.svg"
  desktop_height: "50px"
  desktop_width: "auto"

home: 
  limit_services: 6

collections:
  services:
    output: false
    sort_by: weight
  team:
    output: true

defaults:
  - scope:
      path: ""
      type: "services"
    values:
      layout: "service"
  - scope:
      path: ""
      type: "team"
    values:
      layout: "team"

sass:
  style: compressed # possible values: nested expanded compact compressed

plugins:
  - jekyll-environment-variables
  - jekyll-github-metadata

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - LICENSE.md
  - LICENSE
  - README.md
