[build]
  command = "jekyll build"
  publish = "_site"

[build.environment]
  JEKYLL_ENV = "production"
  RUBY_VERSION = "3.2.2"

[[redirects]]
  from = "/docs"
  to = "https://vdkms-docs.netlify.app"
  status = 200
  force = true